language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

branches:
  only:
    - master
    - /^\d+\.\d+$/
    
before_install:
    - chmod +x phpunit
  
install: composer update $COMPOSER_FLAGS --prefer-dist

script: ./phpunit
